### ISSUE TITLE
Patch implementation wrt ARC003 Standard

### ISSUE THREAD

**Issue by Vidhyanandcs** [IzzyCapNFT/algorand-arc19-auto-mint#1]
I have checked the code and realized that the code is converting the image cid into reserve address. The right implementation would be to pin the json metadata to ipfs and convert corresponding cid to reserve address. I am attaching some examples of popular NFTs for your reference.  If you are willing i can raise a PR.

https://www.nftexplorer.app/asset/812520605
https://ipfs.algonft.tools/ipfs/bafkreibqxhy6xbwmmnmg74md7kq3pfjphiatyyklvvyivlou2gvtdtwopi#arc3

https://www.nftexplorer.app/asset/870683479
https://ipfs.algonft.tools/ipfs/bafkreiczzqv7xe6ho5wdrl24ss7m6hlydtme266rqwtbs32jr2muthnn2m#arc3

**Comment by BeepboyAlgo** [comment]
Hi @Vidhyanandcs,

Thank you for the info! Feel free to open a PR :)

**Comment by BeepboyAlgo** [comment]
Fix on https://github.com/BeepboyAlgo/algorand-arc19-auto-mint/pull/2
